/**
 * POST /api/export/txt
 *
 * Body: { selected, meta }   (same shape the frontend assembles)
 * Returns a plain-text parts list as a downloadable file.
 *
 * POST /api/export/json
 * Returns a structured JSON export of the build.
 */

'use strict';

const { Router } = require('express');
const { body, validationResult } = require('express-validator');
const { calcTotal, partById, priceStr } = require('../engine/recommender');

const router = Router();

const CONN_LABELS = {
  wifi: 'Wi-Fi', ble: 'Bluetooth (BLE)', lora: 'LoRa (long range)',
  gsm: 'GSM / Cellular', none: 'Not sure — auto-pick',
};
const POWER_LABELS  = { battery: 'Battery', solar: 'Solar', mains: 'Mains / USB' };
const BUDGET_LABELS = { budget: 'Budget', standard: 'Standard', premium: 'Premium' };
const EXP_LABELS    = { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced' };

function buildBuyLinks(item) {
  const q = encodeURIComponent(item.name);
  return {
    robu:    `https://robu.in/?s=${q}`,
    amazon:  `https://www.amazon.in/s?k=${q}`,
    flipkart:`https://www.flipkart.com/search?q=${q}`,
    quartz:  `https://quartzcomponents.com/?s=${q}`,
  };
}

function hydrateSelected(selected) {
  const resolve = ids => (ids || []).map(id => partById(id)).filter(Boolean);
  return {
    mcuList:    resolve(selected.mcuList),
    connList:   resolve(selected.connList),
    powerList:  resolve(selected.powerList),
    components: resolve(selected.components),
    regulator:  selected.regulator ? partById(selected.regulator) : null,
  };
}

const validateBody = [
  body('selected').isObject(),
  body('selected.mcuList').isArray({ min: 1 }),
  body('meta').isObject(),
  body('meta.projectName').notEmpty(),
];

// ── POST /api/export/txt ──────────────────────────────────────────────────
router.post('/txt', validateBody, (req, res) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) return res.status(400).json({ ok: false, errors: errors.array() });

  const { selected: rawSelected, meta } = req.body;
  const sel = hydrateSelected(rawSelected);
  const totalAvg = calcTotal(sel);

  const lines = [];
  lines.push('TRACEBOARD — RECOMMENDED PARTS LIST');
  lines.push('='.repeat(40));
  lines.push(`Project      : ${meta.projectName}`);
  lines.push(`Power        : ${POWER_LABELS[meta.power] || meta.power}`);
  lines.push(`Connectivity : ${CONN_LABELS[meta.conn] || meta.conn}`);
  lines.push(`Budget       : ${BUDGET_LABELS[meta.budget] || meta.budget}`);
  lines.push(`Level        : ${EXP_LABELS[meta.exp] || meta.exp}`);
  lines.push('');

  const pushItems = (label, items) => {
    items.forEach(item => {
      const links = buildBuyLinks(item);
      lines.push(`${label} — ${item.name} (${priceStr(item)})`);
      lines.push(`  Robu.in   : ${links.robu}`);
      lines.push(`  Amazon.in : ${links.amazon}`);
      lines.push('');
    });
  };

  pushItems('MICROCONTROLLER', sel.mcuList);
  pushItems('CONNECTIVITY', sel.connList);
  pushItems('COMPONENT', sel.components);
  pushItems('POWER', sel.powerList);
  if (sel.regulator) pushItems('REGULATION', [sel.regulator]);

  lines.push(`ESTIMATED TOTAL: ₹${Math.round(totalAvg * 0.9)}–${Math.round(totalAvg * 1.1)}`);
  lines.push('');
  lines.push('Generated by Traceboard IoT Component Advisor');

  const text = lines.join('\n');
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="traceboard-build.txt"`);
  res.send(text);
});

// ── POST /api/export/json ─────────────────────────────────────────────────
router.post('/json', validateBody, (req, res) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) return res.status(400).json({ ok: false, errors: errors.array() });

  const { selected: rawSelected, meta } = req.body;
  const sel = hydrateSelected(rawSelected);
  const totalAvg = calcTotal(sel);

  const allItems = [
    ...sel.mcuList.map(p  => ({ ...p, role: 'Microcontroller' })),
    ...sel.connList.map(p  => ({ ...p, role: 'Connectivity'    })),
    ...sel.components.map(p => ({ ...p, role: 'Component'       })),
    ...sel.powerList.map(p  => ({ ...p, role: 'Power'           })),
    ...(sel.regulator ? [{ ...sel.regulator, role: 'Voltage Regulator' }] : []),
  ].map(item => ({
    role:       item.role,
    id:         item.id,
    name:       item.name,
    category:   item.cat,
    priceRange: { min: item.price_min, max: item.price_max },
    priceStr:   priceStr(item),
    wiring: {
      interface: item.wiring_iface,
      pins:      item.wiring_pins,
    },
    buyLinks: buildBuyLinks(item),
  }));

  res.setHeader('Content-Disposition', 'attachment; filename="traceboard-build.json"');
  res.json({
    generator:   'Traceboard IoT Component Advisor',
    generatedAt: new Date().toISOString(),
    meta: {
      project:     meta.projectName,
      power:       POWER_LABELS[meta.power]  || meta.power,
      conn:        CONN_LABELS[meta.conn]    || meta.conn,
      budget:      BUDGET_LABELS[meta.budget]|| meta.budget,
      exp:         EXP_LABELS[meta.exp]      || meta.exp,
    },
    estimatedTotal: {
      min: Math.round(totalAvg * 0.9),
      max: Math.round(totalAvg * 1.1),
      currency: 'INR',
    },
    parts: allItems,
  });
});

module.exports = router;
