/**
 * seed.js — populates the parts table from the canonical data set
 * matching the frontend's ALL_PARTS array exactly.
 * Run once on first start; safe to re-run (uses INSERT OR IGNORE).
 */

const PARTS_SEED = [
  // ── MCUs ──────────────────────────────────────────────────────────────────
  {
    id: 'esp32', cat: 'mcu', name: 'ESP32 DevKit V1',
    price_min: 350, price_max: 450,
    tags: ['wifi','ble','budget','standard','beginner','intermediate'],
    description: 'Dual-core, built-in Wi-Fi + Bluetooth, huge community support. The default choice for connected IoT builds.',
    pros: ['Wi-Fi + BLE on one chip','Plenty of GPIO & ADC pins','Deep sleep for battery projects'],
    cons: ['3.3V logic only — mind sensor voltage','Slightly steeper learning curve than Uno'],
    wiring_iface: null, wiring_pins: null,
  },
  {
    id: 'esp8266', cat: 'mcu', name: 'ESP8266 NodeMCU',
    price_min: 200, price_max: 280,
    tags: ['wifi','budget','beginner'],
    description: 'Cheaper Wi-Fi-only cousin of the ESP32. Great for simple, single-purpose connected sensors.',
    pros: ['Very low cost','Small form factor','Well documented for beginners'],
    cons: ['No Bluetooth','Fewer usable GPIO pins','Single core — struggles with heavier logic'],
    wiring_iface: null, wiring_pins: null,
  },
  {
    id: 'uno', cat: 'mcu', name: 'Arduino Uno R3',
    price_min: 450, price_max: 600,
    tags: ['none','budget','beginner'],
    description: 'The classic starting board. No wireless on-board, but unmatched tutorials, shields and community answers.',
    pros: ['Easiest board to debug on','Massive shield/library ecosystem','5V tolerant, simpler sensor wiring'],
    cons: ['No Wi-Fi/BLE — needs an add-on module','Limited memory for complex logic'],
    wiring_iface: null, wiring_pins: null,
  },
  {
    id: 'picow', cat: 'mcu', name: 'Raspberry Pi Pico W',
    price_min: 450, price_max: 550,
    tags: ['wifi','ble','budget','intermediate'],
    description: 'RP2040 dual-core with Wi-Fi and BLE, programmable in MicroPython or C++. Strong performance for the price.',
    pros: ['Dual-core, fast for the price','MicroPython support lowers entry barrier','Good documentation from Raspberry Pi Foundation'],
    cons: ['BLE support is newer/less mature','Smaller community than ESP32'],
    wiring_iface: null, wiring_pins: null,
  },
  {
    id: 'nano33', cat: 'mcu', name: 'Arduino Nano 33 IoT',
    price_min: 1200, price_max: 1500,
    tags: ['wifi','ble','premium','intermediate','advanced'],
    description: 'Compact Arduino-ecosystem board with Wi-Fi, BLE and an on-board IMU. Ideal when you want Arduino tooling with wireless.',
    pros: ['Official Arduino support & IDE integration','On-board 6-axis IMU','Compact for wearable/portable builds'],
    cons: ['Pricier than ESP32 for similar capability','Smaller community than ESP32'],
    wiring_iface: null, wiring_pins: null,
  },
  {
    id: 'bluepill', cat: 'mcu', name: 'STM32 "Blue Pill" F103C8',
    price_min: 250, price_max: 350,
    tags: ['none','budget','advanced'],
    description: '32-bit ARM Cortex-M3 board with strong real-time performance. No wireless — pair with an external module.',
    pros: ['Much faster than 8-bit boards','Great for precise timing/motor control','Very cheap for the compute you get'],
    cons: ['Steeper setup (ST-Link/bootloader)','No built-in wireless','Smaller beginner-friendly ecosystem'],
    wiring_iface: null, wiring_pins: null,
  },

  // ── Connectivity ──────────────────────────────────────────────────────────
  {
    id: 'hc05', cat: 'connectivity', name: 'HC-05 Bluetooth Module',
    price_min: 250, price_max: 350,
    tags: ['ble'],
    description: 'Classic Bluetooth serial module — pairs with a phone app for short-range control.',
    pros: ['Dead simple UART interface','Cheap, widely available'],
    cons: ['Bluetooth Classic, not BLE','~10m range'],
    wiring_iface: 'UART', wiring_pins: 'TX / RX',
  },
  {
    id: 'nrf24', cat: 'connectivity', name: 'NRF24L01 2.4GHz Module',
    price_min: 90, price_max: 150,
    tags: ['mesh'],
    description: 'Low-power 2.4GHz radio for device-to-device mesh links — great for multi-node sensor networks without Wi-Fi.',
    pros: ['Very low cost','Low power draw','Good for node-to-node mesh'],
    cons: ['Needs a second unit to talk to','Shorter range than LoRa'],
    wiring_iface: 'SPI', wiring_pins: 'MOSI / MISO / SCK / CE / CSN',
  },
  {
    id: 'sim800l', cat: 'connectivity', name: 'SIM800L GSM/GPRS Module',
    price_min: 450, price_max: 650,
    tags: ['gsm'],
    description: 'Cellular connectivity for locations with no local Wi-Fi — sends data over 2G/GPRS.',
    pros: ['Works anywhere with cell coverage','Can send SMS alerts directly'],
    cons: ['Needs a SIM + recharge','Power-hungry during transmit bursts'],
    wiring_iface: 'UART', wiring_pins: 'TX / RX (separate 4V supply)',
  },
  {
    id: 'lora', cat: 'connectivity', name: 'LoRa Ra-02 (SX1278)',
    price_min: 350, price_max: 500,
    tags: ['lora'],
    description: 'Long-range, low-power radio — kilometres of range at low bitrate. The go-to for rural/agri deployments.',
    pros: ['Multi-km range, line of sight','Very low power draw','No recurring SIM cost'],
    cons: ['Needs a matching receiver/gateway','Low data rate — telemetry only'],
    wiring_iface: 'SPI', wiring_pins: 'MOSI / MISO / SCK / NSS / RST / DIO0',
  },

  // ── Sensors ───────────────────────────────────────────────────────────────
  {
    id: 'dht11', cat: 'sensor', name: 'DHT11 Temp & Humidity',
    price_min: 80, price_max: 120,
    tags: ['budget'],
    description: 'Basic combined temperature/humidity sensor. ±2°C, ±5% RH accuracy — fine for casual monitoring.',
    pros: ['Very cheap','Single wire, easy wiring'],
    cons: ['Lower accuracy','Slow sample rate (~1Hz)'],
    wiring_iface: 'Digital', wiring_pins: '1 digital pin + pull-up',
  },
  {
    id: 'dht22', cat: 'sensor', name: 'DHT22 Temp & Humidity',
    price_min: 250, price_max: 350,
    tags: ['standard'],
    description: 'Precision upgrade over the DHT11 — ±0.5°C, ±2–5% RH, wider operating range.',
    pros: ['Noticeably more accurate','Wider temp/humidity range'],
    cons: ['Costs ~3x the DHT11'],
    wiring_iface: 'Digital', wiring_pins: '1 digital pin + pull-up',
  },
  {
    id: 'pir', cat: 'sensor', name: 'HC-SR501 PIR Motion Sensor',
    price_min: 60, price_max: 90,
    tags: ['budget'],
    description: 'Passive infrared sensor that triggers on human/animal movement within its cone.',
    pros: ['Extremely cheap','Adjustable sensitivity & delay'],
    cons: ['False triggers near heat sources','No direction/distance data'],
    wiring_iface: 'Digital', wiring_pins: '1 digital input pin',
  },
  {
    id: 'bmp280', cat: 'sensor', name: 'BMP280 Pressure/Altitude',
    price_min: 150, price_max: 220,
    tags: ['standard'],
    description: 'Barometric pressure sensor, also derives altitude — useful for weather station builds.',
    pros: ['I2C, easy to wire alongside other sensors','Good accuracy for the price'],
    cons: ['No humidity sensing (pair with DHT22)'],
    wiring_iface: 'I2C', wiring_pins: 'SDA / SCL',
  },
  {
    id: 'mq135', cat: 'sensor', name: 'MQ-135 Air Quality Sensor',
    price_min: 150, price_max: 200,
    tags: ['budget'],
    description: 'Detects NH3, NOx, CO2, benzene and smoke — general-purpose air quality gauge.',
    pros: ['Detects a broad range of gases','Cheap and easy to source'],
    cons: ['Needs warm-up time & calibration','Analog output, not a precise ppm reading out of the box'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'rain', cat: 'sensor', name: 'Rain Drop Sensor Module',
    price_min: 60, price_max: 90,
    tags: ['budget'],
    description: 'Detects rainfall via a conductive board — digital rain/no-rain plus analog intensity.',
    pros: ['Very cheap','Simple digital + analog output'],
    cons: ['Board corrodes over time outdoors'],
    wiring_iface: 'Analog', wiring_pins: '1 analog + 1 digital pin',
  },
  {
    id: 'soilcap', cat: 'sensor', name: 'Capacitive Soil Moisture v2.0',
    price_min: 90, price_max: 150,
    tags: ['budget'],
    description: 'Capacitive sensing avoids the corrosion that plagues resistive probes — the standard pick for soil moisture.',
    pros: ['Corrosion-resistant, lasts in soil long-term','Analog output, easy to calibrate'],
    cons: ['Slightly pricier than resistive probes'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'soilres', cat: 'sensor', name: 'Resistive Soil Moisture Sensor',
    price_min: 40, price_max: 70,
    tags: ['budget'],
    description: 'Two-prong resistive probe. Cheapest option, but the exposed metal corrodes within weeks of continuous burial.',
    pros: ['Lowest cost option'],
    cons: ['Corrodes with prolonged soil contact','Needs replacement over a growing season'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'npk', cat: 'sensor', name: 'Soil NPK Sensor (RS485)',
    price_min: 2500, price_max: 3500,
    tags: ['premium'],
    description: 'Measures nitrogen, phosphorus and potassium levels directly — for serious precision-agriculture builds.',
    pros: ['Real nutrient data, not just moisture','Industrial RS485 interface'],
    cons: ['Significant cost jump','Needs an RS485-to-serial adapter'],
    wiring_iface: 'UART', wiring_pins: 'RS485→TTL: TX / RX',
  },
  {
    id: 'flow', cat: 'sensor', name: 'YF-S201 Water Flow Sensor',
    price_min: 250, price_max: 350,
    tags: ['standard'],
    description: 'Hall-effect flow sensor for irrigation lines — pulses proportional to flow rate.',
    pros: ['Direct flow measurement for auto-irrigation','Simple pulse-counting interface'],
    cons: ['Needs plumbing fitting to install inline'],
    wiring_iface: 'Digital', wiring_pins: '1 interrupt-capable pin',
  },
  {
    id: 'max30102', cat: 'sensor', name: 'MAX30102 Pulse Ox + HR',
    price_min: 250, price_max: 400,
    tags: ['standard'],
    description: 'Optical sensor for heart rate and blood-oxygen estimation — the core sensor behind most DIY wearables.',
    pros: ['I2C, low pin count','Same sensing principle as commercial fitness bands'],
    cons: ['Needs steady skin contact for clean readings'],
    wiring_iface: 'I2C', wiring_pins: 'SDA / SCL',
  },
  {
    id: 'mpu6050', cat: 'sensor', name: 'MPU6050 Accel + Gyro',
    price_min: 150, price_max: 220,
    tags: ['budget'],
    description: '6-axis accelerometer + gyroscope. Used for motion tracking, fall detection, orientation and robot balancing.',
    pros: ['Very cheap for 6-axis sensing','I2C, well-documented libraries'],
    cons: ['Drift over time without a magnetometer'],
    wiring_iface: 'I2C', wiring_pins: 'SDA / SCL',
  },
  {
    id: 'gsr', cat: 'sensor', name: 'GSR (Galvanic Skin Response) Sensor',
    price_min: 300, price_max: 450,
    tags: ['premium'],
    description: 'Measures skin conductance changes tied to sweat gland activity — a proxy for stress/arousal.',
    pros: ['Enables stress-tracking features','Simple analog output'],
    cons: ['Noisy signal, needs filtering/calibration'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'espcam', cat: 'sensor', name: 'ESP32-CAM Module',
    price_min: 600, price_max: 800,
    tags: ['standard'],
    description: 'ESP32 with an integrated camera — stream or capture stills for visual monitoring nodes.',
    pros: ['Wi-Fi + camera on one board','Can stream to a browser directly'],
    cons: ['No USB port on most boards — needs an FTDI programmer','Camera quality is basic'],
    wiring_iface: 'Power', wiring_pins: 'Onboard camera — 5V / GND only',
  },
  {
    id: 'rfid', cat: 'sensor', name: 'RC522 RFID Reader',
    price_min: 90, price_max: 150,
    tags: ['budget'],
    description: '13.56MHz RFID/NFC reader for tag-based access control.',
    pros: ['Cheap, reliable tag reading','SPI interface, fast'],
    cons: ['Short read range (~3cm)'],
    wiring_iface: 'SPI', wiring_pins: 'MOSI / MISO / SCK / SDA / RST',
  },
  {
    id: 'reed', cat: 'sensor', name: 'Magnetic Reed Switch',
    price_min: 30, price_max: 60,
    tags: ['budget'],
    description: 'Simple door/window contact sensor — closes a circuit when a magnet is nearby.',
    pros: ['Extremely cheap and reliable','No calibration needed'],
    cons: ['Binary output only — open/closed'],
    wiring_iface: 'Digital', wiring_pins: '1 digital input pin',
  },
  {
    id: 'ultrasonic', cat: 'sensor', name: 'HC-SR04 Ultrasonic Distance',
    price_min: 60, price_max: 90,
    tags: ['budget'],
    description: 'Time-of-flight distance sensing via ultrasound — the standard obstacle sensor for small robots.',
    pros: ['Cheap and accurate to ~3mm','Simple trigger/echo interface'],
    cons: ['Struggles with soft/angled surfaces'],
    wiring_iface: 'Digital', wiring_pins: 'TRIG / ECHO pins',
  },
  {
    id: 'irline', cat: 'sensor', name: 'IR Line-Follow Sensor Pair',
    price_min: 60, price_max: 100,
    tags: ['budget'],
    description: 'Reflective IR pair for detecting a line on the ground — core of any line-following robot.',
    pros: ['Very cheap, plug-and-play','Digital output, minimal code'],
    cons: ['Sensitive to ambient light conditions'],
    wiring_iface: 'Digital', wiring_pins: '2 digital input pins',
  },
  {
    id: 'acs712', cat: 'sensor', name: 'ACS712 Current Sensor',
    price_min: 150, price_max: 220,
    tags: ['budget'],
    description: 'Hall-effect current sensor — measures AC/DC current for load monitoring.',
    pros: ['Cheap, easy analog interface','Multiple current ranges available'],
    cons: ['Needs calibration for accurate readings'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'zmpt101b', cat: 'sensor', name: 'ZMPT101B Voltage Sensor',
    price_min: 200, price_max: 300,
    tags: ['standard'],
    description: 'AC mains voltage sensing module, typically paired with ACS712 for full power monitoring.',
    pros: ['Accurate mains voltage sensing','Isolated from mains for safety'],
    cons: ['Needs a trim-pot calibration step'],
    wiring_iface: 'Analog', wiring_pins: '1 analog input (ADC)',
  },
  {
    id: 'pzem', cat: 'sensor', name: 'PZEM-004T Energy Meter',
    price_min: 700, price_max: 900,
    tags: ['premium'],
    description: 'All-in-one voltage, current, power, energy and frequency meter with a UART interface — skips separate calibration.',
    pros: ['One module replaces current+voltage sensor pair','Pre-calibrated, UART data ready to parse'],
    cons: ['Higher upfront cost'],
    wiring_iface: 'UART', wiring_pins: 'TX / RX',
  },

  // ── Actuators ─────────────────────────────────────────────────────────────
  {
    id: 'servo', cat: 'actuator', name: 'SG90 Micro Servo',
    price_min: 100, price_max: 150,
    tags: ['budget'],
    description: 'Small 180° servo motor for actuation — steering, arms, latch mechanisms.',
    pros: ['Cheap and widely supported','Precise position control'],
    cons: ['Limited torque — light loads only'],
    wiring_iface: 'PWM', wiring_pins: '1 PWM-capable pin',
  },
  {
    id: 'relay', cat: 'actuator', name: '1/2/4-Channel Relay Module',
    price_min: 60, price_max: 150,
    tags: ['budget'],
    description: 'Lets your MCU switch mains-voltage appliances safely via an isolated relay.',
    pros: ['Switches real household loads','Opto-isolated for safety'],
    cons: ['Mains wiring requires care — double-check ratings'],
    wiring_iface: 'Digital', wiring_pins: '1 digital output per channel',
  },

  // ── Power ─────────────────────────────────────────────────────────────────
  {
    id: 'li18650', cat: 'power', name: '18650 Li-ion Cell + TP4056',
    price_min: 150, price_max: 250,
    tags: ['battery'],
    description: 'Rechargeable 3.7V cell with a USB-C charge/protection board — the standard battery combo for portable builds.',
    pros: ['Rechargeable, good capacity (~2000-3000mAh)','TP4056 handles safe charging'],
    cons: ['Bulkier than LiPo pouch cells'],
    wiring_iface: 'Power', wiring_pins: 'VIN / GND via TP4056 OUT',
  },
  {
    id: 'lipo', cat: 'power', name: 'LiPo 3.7V 1000mAh + Charger',
    price_min: 250, price_max: 350,
    tags: ['battery'],
    description: 'Slim pouch-cell battery — the better fit when the build needs to be worn or stay compact.',
    pros: ['Thin, flexible form factor','Good for wearables/compact enclosures'],
    cons: ['Needs careful handling — punctures are a fire risk'],
    wiring_iface: 'Power', wiring_pins: 'VIN / GND via charger board',
  },
  {
    id: 'solar', cat: 'power', name: '6V 1W Solar Panel + Charge Controller',
    price_min: 300, price_max: 450,
    tags: ['solar'],
    description: 'Small solar panel with a basic charge controller — for outdoor, off-grid deployments.',
    pros: ['No recurring power cost','Suited to remote field/farm sites'],
    cons: ['Needs a battery buffer for night-time operation','Output varies with weather'],
    wiring_iface: 'Power', wiring_pins: 'Battery in via charge controller',
  },
  {
    id: 'usb', cat: 'power', name: '5V USB Adapter / Power Bank',
    price_min: 150, price_max: 300,
    tags: ['mains'],
    description: 'Simplest option — steady 5V from a wall adapter or power bank, no charging circuit to design.',
    pros: ['Simplest, most reliable power','No battery management needed'],
    cons: ['Tethered — not truly portable'],
    wiring_iface: 'Power', wiring_pins: '5V / GND via VIN or USB',
  },
  {
    id: 'ams1117', cat: 'power', name: 'AMS1117 3.3V Regulator Module',
    price_min: 20, price_max: 40,
    tags: ['battery','solar'],
    description: 'Small linear regulator board — steps battery voltage down cleanly to the 3.3V most MCUs and sensors need.',
    pros: ['Cheap safety net for clean 3.3V','Prevents brownout resets under load'],
    cons: ['Wastes some energy as heat vs. a switching regulator'],
    wiring_iface: 'Power', wiring_pins: 'IN → OUT 3.3V / GND',
  },
];

module.exports = { PARTS_SEED };
